version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: musify
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/musify

  client:
    build: ./client
    ports:
      - "4200:80"
    depends_on:
      - server

volumes:
  mongo_data:
